library(data.table)
library(ggplot2)
library(ggtree)
library(ape)
library(parallel)
library(dplyr)
library(tidytree)

source("github/code/read_blast.R")
source("github/code/ortho_blast.R")
source("github/code/predict_MSH6_orthologs.R")
source("github/code/get_protein_location.R")
source("github/code/annotate_domain.R")
source("github/code/read_interproscan.R")
source("github/code/check_tblastn.R")
source("github/code/make_MSH6_organism_table.R")
