library(data.table)
library(ggplot2)
library(ggtree)
library(ape)
library(parallel)
library(dplyr)
library(tidytree)

source("code/read_blast.R")
source("code/ortho_blast.R")
source("code/predict_MSH6_orthologs.R")
source("code/get_protein_location.R")
source("code/annotate_domain.R")
source("code/read_interproscan.R")
source("code/check_tblastn.R")
source("code/make_MSH6_organism_table.R")
